// <auto-generated />
using System;
using KillasTravel.Infrastructure.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KillasTravel.Infrastructure.Migrations
{
    [DbContext(typeof(KillasTravelDbContext))]
    partial class KillasTravelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KillasTravel.Domain.Entities.Alojamiento", b =>
                {
                    b.Property<int>("AlojamientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlojamientoID"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinoID")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("AlojamientoID");

                    b.HasIndex("DestinoID");

                    b.ToTable("Alojamientos");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Destino", b =>
                {
                    b.Property<int>("DestinoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinoID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.HasKey("DestinoID");

                    b.HasIndex("RegionID");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.DetalleOrden", b =>
                {
                    b.Property<int>("DetalleOrdenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleOrdenID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenID")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetalleOrdenID");

                    b.HasIndex("OrdenID");

                    b.ToTable("DetalleOrden");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Orden", b =>
                {
                    b.Property<int>("OrdenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenID"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("OrdenID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Paquete", b =>
                {
                    b.Property<int>("PaqueteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PaqueteID");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.PaqueteServicio", b =>
                {
                    b.Property<int>("PaqueteServicioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteServicioID"));

                    b.Property<int?>("AlojamientoID")
                        .HasColumnType("int");

                    b.Property<int>("PaqueteID")
                        .HasColumnType("int");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TourID")
                        .HasColumnType("int");

                    b.Property<int?>("TransporteID")
                        .HasColumnType("int");

                    b.HasKey("PaqueteServicioID");

                    b.HasIndex("AlojamientoID");

                    b.HasIndex("PaqueteID");

                    b.HasIndex("TourID");

                    b.HasIndex("TransporteID");

                    b.ToTable("PaqueteServicios");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionID");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Tour", b =>
                {
                    b.Property<int>("TourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinoID")
                        .HasColumnType("int");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("TourID");

                    b.HasIndex("DestinoID");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Transporte", b =>
                {
                    b.Property<int>("TransporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporteID"));

                    b.Property<int>("DestinoFinalDestinoID")
                        .HasColumnType("int");

                    b.Property<string>("NombreRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrigenDestinoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransporteID");

                    b.HasIndex("DestinoFinalDestinoID");

                    b.HasIndex("OrigenDestinoID");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.TransporteTarifa", b =>
                {
                    b.Property<int>("TarifaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarifaID"));

                    b.Property<string>("DescripcionServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TransporteID")
                        .HasColumnType("int");

                    b.HasKey("TarifaID");

                    b.HasIndex("TransporteID");

                    b.ToTable("TransporteTarifas");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Alojamiento", b =>
                {
                    b.HasOne("KillasTravel.Domain.Entities.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoID");

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Destino", b =>
                {
                    b.HasOne("KillasTravel.Domain.Entities.Region", "Region")
                        .WithMany("Destinos")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.DetalleOrden", b =>
                {
                    b.HasOne("KillasTravel.Domain.Entities.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Orden", b =>
                {
                    b.HasOne("KillasTravel.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ordenes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.PaqueteServicio", b =>
                {
                    b.HasOne("KillasTravel.Domain.Entities.Alojamiento", "Alojamiento")
                        .WithMany()
                        .HasForeignKey("AlojamientoID");

                    b.HasOne("KillasTravel.Domain.Entities.Paquete", "Paquete")
                        .WithMany("ServiciosIncluidos")
                        .HasForeignKey("PaqueteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KillasTravel.Domain.Entities.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourID");

                    b.HasOne("KillasTravel.Domain.Entities.Transporte", "Transporte")
                        .WithMany()
                        .HasForeignKey("TransporteID");

                    b.Navigation("Alojamiento");

                    b.Navigation("Paquete");

                    b.Navigation("Tour");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Tour", b =>
                {
                    b.HasOne("KillasTravel.Domain.Entities.Destino", "Destino")
                        .WithMany("Tours")
                        .HasForeignKey("DestinoID");

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Transporte", b =>
                {
                    b.HasOne("KillasTravel.Domain.Entities.Destino", "DestinoFinal")
                        .WithMany()
                        .HasForeignKey("DestinoFinalDestinoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KillasTravel.Domain.Entities.Destino", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenDestinoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinoFinal");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.TransporteTarifa", b =>
                {
                    b.HasOne("KillasTravel.Domain.Entities.Transporte", "Transporte")
                        .WithMany("Tarifas")
                        .HasForeignKey("TransporteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Destino", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Paquete", b =>
                {
                    b.Navigation("ServiciosIncluidos");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Region", b =>
                {
                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Transporte", b =>
                {
                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("KillasTravel.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
